# -*- coding: utf-8 -*-
# Part of Odoo Module Developed by 73lines
# See LICENSE file for full copyright and licensing details.
{
    'name': 'Business Snippet Blocks Core',
    'description': 'Business Snippet Blocks Core',
    'category': "Business",
    'author': "73Lines",
    'website': "https://www.73lines.com/",
    'version': "13.0.1.0.1",

    'data': [
        'views/assets.xml',

        # Blank Structure Snippets
        'views/snippets/blank_grid_snippets/blank_grid_snippet_1.xml',
        'views/snippets/blank_grid_snippets/blank_grid_snippet_2.xml',
        'views/snippets/blank_grid_snippets/blank_grid_snippet_3.xml',
        'views/snippets/blank_grid_snippets/blank_grid_snippet_4.xml',
        'views/snippets/blank_grid_snippets/blank_grid_snippet_5.xml',
        'views/snippets/blank_grid_snippets/blank_grid_snippet_6.xml',
        'views/snippets/blank_grid_snippets/blank_grid_snippet_7.xml',

        # Mid Headers Snippets
        'views/snippets/mid_headers/mid_header_dark_1.xml',
        'views/snippets/mid_headers/mid_header_dark_2.xml',
        'views/snippets/mid_headers/mid_header_dark_3.xml',
        'views/snippets/mid_headers/mid_header_dark_4.xml',
        'views/snippets/mid_headers/mid_header_dark_5.xml',
        'views/snippets/mid_headers/mid_header_light_1.xml',
        'views/snippets/mid_headers/mid_header_light_2.xml',
        'views/snippets/mid_headers/mid_header_light_3.xml',
        'views/snippets/mid_headers/mid_header_light_4.xml',
        'views/snippets/mid_headers/mid_header_light_5.xml',


        #Mega Menu Snippet
        'views/snippets/mega_menu/mega_menu_d1.xml',
        'views/snippets/mega_menu/mega_menu_d2.xml',
        'views/snippets/mega_menu/mega_menu_d3.xml',
        'views/snippets/mega_menu/mega_menu_d4.xml',
        'views/snippets/mega_menu/mega_menu_d5.xml',
        'views/snippets/mega_menu/mega_menu_d6.xml',
        'views/snippets/mega_menu/mega_menu_d7.xml',
        'views/snippets/mega_menu/mega_menu_d8.xml',
        'views/snippets/mega_menu/mega_menu_d9.xml',
        'views/snippets/mega_menu/mega_menu_d10.xml',
        'views/snippets/mega_menu/list_without_icon.xml',
        'views/snippets/mega_menu/list_with_icon.xml',
        'views/snippets/mega_menu/mega_menu_img_transition_d1.xml',
        'views/snippets/mega_menu/mega_menu_img_transition_d2.xml',
        'views/snippets/mega_menu/mega_menu_img_transition_d3.xml',
        'views/snippets/mega_menu/mega_menu_img_transition_d4.xml',
        'views/snippets/mega_menu/mega_menu_img_transition_d5.xml',
        'views/snippets/mega_menu/mega_menu_img_transition_d6.xml',

        # Banners Snippet
        'views/snippets/banners/banner_d1.xml',
        'views/snippets/banners/banner_d2.xml',
        'views/snippets/banners/banner_d3.xml',
        'views/snippets/banners/banner_d4.xml',
        'views/snippets/banners/banner_d5.xml',
        'views/snippets/banners/banner_d6.xml',
        'views/snippets/banners/banner_d7.xml',
        'views/snippets/banners/banner_d8.xml',
        'views/snippets/banners/banner_d9.xml',
        'views/snippets/banners/banner_d10.xml',
        'views/snippets/banners/banner_d11.xml',

        # Snippets Grid
        'views/snippets/snippets_grid/grid_1.xml',
        'views/snippets/snippets_grid/grid_2.xml',
        'views/snippets/snippets_grid/grid_3.xml',
        'views/snippets/snippets_grid/grid_4.xml',
        'views/snippets/snippets_grid/grid_5.xml',
        'views/snippets/snippets_grid/grid_6.xml',
        'views/snippets/snippets_grid/grid_7.xml',
        'views/snippets/snippets_grid/grid_8.xml',
        'views/snippets/snippets_grid/grid_9.xml',
        'views/snippets/snippets_grid/grid_10.xml',
        'views/snippets/snippets_grid/grid_11.xml',
        'views/snippets/snippets_grid/grid_12.xml',
        'views/snippets/snippets_grid/grid_13.xml',
        'views/snippets/snippets_grid/grid_14.xml',
        'views/snippets/snippets_grid/grid_15.xml',
        'views/snippets/snippets_grid/grid_16.xml',
        'views/snippets/snippets_grid/grid_17.xml',
        'views/snippets/snippets_grid/grid_18.xml',
        'views/snippets/snippets_grid/grid_19.xml',
        'views/snippets/snippets_grid/grid_20.xml',
        'views/snippets/snippets_grid/grid_21.xml',
        'views/snippets/snippets_grid/grid_22.xml',
        'views/snippets/snippets_grid/grid_23.xml',
        'views/snippets/snippets_grid/grid_24.xml',
        'views/snippets/snippets_grid/grid_25.xml',
        'views/snippets/snippets_grid/grid_26.xml',
        'views/snippets/snippets_grid/grid_27.xml',
        'views/snippets/snippets_grid/grid_28.xml',
        'views/snippets/snippets_grid/grid_29.xml',
        'views/snippets/snippets_grid/grid_30.xml',

        # Center Block Snippets
        'views/snippets/center_content/center_content_1.xml',
        'views/snippets/center_content/center_content_2.xml',
        'views/snippets/center_content/center_content_3.xml',
        'views/snippets/center_content/center_content_4.xml',
        'views/snippets/center_content/center_content_5.xml',
        'views/snippets/center_content/center_content_6.xml',
        'views/snippets/center_content/center_content_7.xml',
        'views/snippets/center_content/center_content_8.xml',
        'views/snippets/center_content/center_content_9.xml',
        'views/snippets/center_content/center_content_10.xml',
        'views/snippets/center_content/center_content_11.xml',
        'views/snippets/center_content/center_content_12.xml',
        'views/snippets/center_content/center_content_13.xml',
        'views/snippets/center_content/center_content_14.xml',
        'views/snippets/center_content/center_content_15.xml',
        'views/snippets/center_content/center_content_16.xml',
        'views/snippets/center_content/center_content_17.xml',
        'views/snippets/center_content/center_content_18.xml',
        'views/snippets/center_content/center_content_19.xml',
        'views/snippets/center_content/center_content_20.xml',
        'views/snippets/center_content/center_content_21.xml',
        'views/snippets/center_content/center_content_22.xml',
        'views/snippets/center_content/center_content_23.xml',
        'views/snippets/center_content/center_content_24.xml',
        'views/snippets/center_content/center_content_25.xml',
        'views/snippets/center_content/center_content_26.xml',

        # Snippets Left Content
        'views/snippets/snippets_left_content/left_content_1.xml',
        'views/snippets/snippets_left_content/left_content_2.xml',
        'views/snippets/snippets_left_content/left_content_3.xml',
        'views/snippets/snippets_left_content/left_content_4.xml',
        'views/snippets/snippets_left_content/left_content_5.xml',
        'views/snippets/snippets_left_content/left_content_6.xml',
        'views/snippets/snippets_left_content/left_content_7.xml',
        'views/snippets/snippets_left_content/left_content_8.xml',
        'views/snippets/snippets_left_content/left_content_9.xml',
        'views/snippets/snippets_left_content/left_content_10.xml',
        'views/snippets/snippets_left_content/left_content_11.xml',
        'views/snippets/snippets_left_content/left_content_12.xml',
        'views/snippets/snippets_left_content/left_content_13.xml',
        'views/snippets/snippets_left_content/left_content_14.xml',
        'views/snippets/snippets_left_content/left_content_15.xml',
        'views/snippets/snippets_left_content/left_content_16.xml',
        'views/snippets/snippets_left_content/left_content_17.xml',
        'views/snippets/snippets_left_content/left_content_18.xml',
        'views/snippets/snippets_left_content/left_content_19.xml',
        'views/snippets/snippets_left_content/left_content_20.xml',
        'views/snippets/snippets_left_content/left_content_21.xml',
        'views/snippets/snippets_left_content/left_content_22.xml',
        'views/snippets/snippets_left_content/left_content_23.xml',
        'views/snippets/snippets_left_content/left_content_24.xml',
        'views/snippets/snippets_left_content/left_content_25.xml',
        'views/snippets/snippets_left_content/left_content_26.xml',
        'views/snippets/snippets_left_content/left_content_27.xml',
        'views/snippets/snippets_left_content/left_content_28.xml',

        # Snippets Right Content
        'views/snippets/snippets_right_content/right_content_1.xml',
        'views/snippets/snippets_right_content/right_content_2.xml',
        'views/snippets/snippets_right_content/right_content_3.xml',
        'views/snippets/snippets_right_content/right_content_4.xml',
        'views/snippets/snippets_right_content/right_content_5.xml',
        'views/snippets/snippets_right_content/right_content_6.xml',
        'views/snippets/snippets_right_content/right_content_7.xml',
        'views/snippets/snippets_right_content/right_content_8.xml',
        'views/snippets/snippets_right_content/right_content_9.xml',
        'views/snippets/snippets_right_content/right_content_10.xml',
        'views/snippets/snippets_right_content/right_content_11.xml',
        'views/snippets/snippets_right_content/right_content_12.xml',
        'views/snippets/snippets_right_content/right_content_13.xml',
        'views/snippets/snippets_right_content/right_content_14.xml',
        'views/snippets/snippets_right_content/right_content_15.xml',
        'views/snippets/snippets_right_content/right_content_16.xml',
        'views/snippets/snippets_right_content/right_content_17.xml',
        'views/snippets/snippets_right_content/right_content_18.xml',
        'views/snippets/snippets_right_content/right_content_19.xml',
        'views/snippets/snippets_right_content/right_content_20.xml',
        'views/snippets/snippets_right_content/right_content_21.xml',
        'views/snippets/snippets_right_content/right_content_22.xml',
        'views/snippets/snippets_right_content/right_content_23.xml',
        'views/snippets/snippets_right_content/right_content_24.xml',
        'views/snippets/snippets_right_content/right_content_25.xml',
        'views/snippets/snippets_right_content/right_content_26.xml',
        'views/snippets/snippets_right_content/right_content_27.xml',
        'views/snippets/snippets_right_content/right_content_28.xml',

        #About Us
        'views/snippets/about_us/about_1.xml',
		'views/snippets/about_us/about_2.xml',
		'views/snippets/about_us/about_3.xml',
		'views/snippets/about_us/about_4.xml',
		'views/snippets/about_us/about_5.xml',
		'views/snippets/about_us/about_6.xml',

        # Tab Snippets
        'views/snippets/tabs/tab_1.xml',
        'views/snippets/tabs/tab_2.xml',
        'views/snippets/tabs/tab_3.xml',
        'views/snippets/tabs/tab_4.xml',
        'views/snippets/tabs/tab_5.xml',
        'views/snippets/tabs/tab_6.xml',
        'views/snippets/tabs/tab_7.xml',
        'views/snippets/tabs/tab_8.xml',
        'views/snippets/tabs/tab_9.xml',
        'views/snippets/tabs/tab_10.xml',


        # accordion Snippets
        'views/snippets/accordion/accordion_1.xml',
        'views/snippets/accordion/accordion_2.xml',
        'views/snippets/accordion/accordion_3.xml',
        'views/snippets/accordion/accordion_4.xml',
        'views/snippets/accordion/accordion_5.xml',
        'views/snippets/accordion/accordion_6.xml',
        'views/snippets/accordion/accordion_7.xml',
        'views/snippets/accordion/accordion_8.xml',
        'views/snippets/accordion/accordion_9.xml',
        'views/snippets/accordion/accordion_10.xml',
        'views/snippets/accordion/accordion_11.xml',


        #Process Step
        'views/snippets/process_step/process_step_1.xml',
        'views/snippets/process_step/process_step_2.xml',
        'views/snippets/process_step/process_step_3.xml',
        'views/snippets/process_step/process_step_4.xml',
        'views/snippets/process_step/process_step_5.xml',
        'views/snippets/process_step/process_step_6.xml',
        'views/snippets/process_step/process_step_7.xml',
        'views/snippets/process_step/process_step_8.xml',
        'views/snippets/process_step/process_step_9.xml',
        'views/snippets/process_step/process_step_10.xml',
        'views/snippets/process_step/process_step_11.xml',
        'views/snippets/process_step/process_step_12.xml',
        'views/snippets/process_step/process_step_13.xml',
        'views/snippets/process_step/process_step_14.xml',
        'views/snippets/process_step/process_step_15.xml',

        #Features New
        'views/snippets/features_new/feature_1.xml',
        'views/snippets/features_new/feature_2.xml',
        'views/snippets/features_new/feature_3.xml',
        'views/snippets/features_new/feature_4.xml',
        'views/snippets/features_new/feature_5.xml',
        'views/snippets/features_new/feature_6.xml',
        'views/snippets/features_new/feature_7.xml',
        'views/snippets/features_new/feature_8.xml',
        'views/snippets/features_new/feature_9.xml',
        'views/snippets/features_new/feature_10.xml',
        'views/snippets/features_new/feature_11.xml',
        'views/snippets/features_new/feature_12.xml',
        'views/snippets/features_new/feature_13.xml',
        'views/snippets/features_new/feature_14.xml',
        'views/snippets/features_new/feature_15.xml',
        'views/snippets/features_new/feature_16.xml',
        'views/snippets/features_new/feature_17.xml',
        'views/snippets/features_new/feature_18.xml',
        'views/snippets/features_new/feature_19.xml',
        'views/snippets/features_new/feature_20.xml',
        'views/snippets/features_new/feature_21.xml',
        'views/snippets/features_new/feature_22.xml',
        'views/snippets/features_new/feature_23.xml',
        'views/snippets/features_new/feature_24.xml',
        'views/snippets/features_new/feature_25.xml',
        'views/snippets/features_new/feature_26.xml',
        'views/snippets/features_new/feature_27.xml',
        'views/snippets/features_new/feature_28.xml',
        'views/snippets/features_new/feature_29.xml',
        'views/snippets/features_new/feature_30.xml',
        'views/snippets/features_new/feature_31.xml',
        'views/snippets/features_new/feature_32.xml',
        'views/snippets/features_new/feature_33.xml',
        'views/snippets/features_new/feature_34.xml',
        'views/snippets/features_new/feature_35.xml',
        'views/snippets/features_new/feature_36.xml',
        'views/snippets/features_new/feature_37.xml',

        #counter
        'views/snippets/counter/counter_1.xml',
        'views/snippets/counter/counter_2.xml',
        'views/snippets/counter/counter_3.xml',
        'views/snippets/counter/counter_4.xml',
        'views/snippets/counter/counter_5.xml',
        'views/snippets/counter/counter_6.xml',
        'views/snippets/counter/counter_7.xml',
        'views/snippets/counter/counter_8.xml',
        'views/snippets/counter/counter_9.xml',
        'views/snippets/counter/counter_10.xml',
        'views/snippets/counter/counter_11.xml',
        'views/snippets/counter/counter_12.xml',
        'views/snippets/counter/counter_13.xml',
        'views/snippets/counter/counter_14.xml',
        'views/snippets/counter/counter_15.xml',

        # Image Block
        'views/snippets/image_blocks/img_block_1.xml',
        'views/snippets/image_blocks/img_block_2.xml',
        'views/snippets/image_blocks/img_block_3.xml',
        'views/snippets/image_blocks/img_block_4.xml',
        'views/snippets/image_blocks/img_block_5.xml',
        'views/snippets/image_blocks/img_block_6.xml',
        'views/snippets/image_blocks/img_block_7.xml',
        'views/snippets/image_blocks/img_block_8.xml',
        'views/snippets/image_blocks/img_block_9.xml',
        'views/snippets/image_blocks/img_block_10.xml',
        'views/snippets/image_blocks/img_block_11.xml',

        #Snippets Portfolio
        'views/snippets/snippets_portfolio/portfolio_1.xml',
        'views/snippets/snippets_portfolio/portfolio_2.xml',
        'views/snippets/snippets_portfolio/portfolio_3.xml',
        'views/snippets/snippets_portfolio/portfolio_4.xml',
        'views/snippets/snippets_portfolio/portfolio_5.xml',
        'views/snippets/snippets_portfolio/portfolio_6.xml',
        'views/snippets/snippets_portfolio/portfolio_7.xml',
        'views/snippets/snippets_portfolio/portfolio_8.xml',
        'views/snippets/snippets_portfolio/portfolio_9.xml',

        # Team New
        'views/snippets/team_new/team_1.xml',
        'views/snippets/team_new/team_2.xml',
        'views/snippets/team_new/team_3.xml',
        'views/snippets/team_new/team_4.xml',
        'views/snippets/team_new/team_5.xml',
        'views/snippets/team_new/team_6.xml',
        'views/snippets/team_new/team_7.xml',
        'views/snippets/team_new/team_8.xml',
        'views/snippets/team_new/team_9.xml',
        'views/snippets/team_new/team_10.xml',
        'views/snippets/team_new/team_11.xml',
        'views/snippets/team_new/team_12.xml',

        # Testimonials New
        'views/snippets/testimonials_new/testimonial_1.xml',
        'views/snippets/testimonials_new/testimonial_2.xml',
        'views/snippets/testimonials_new/testimonial_3.xml',
        'views/snippets/testimonials_new/testimonial_4.xml',
        'views/snippets/testimonials_new/testimonial_5.xml',
        'views/snippets/testimonials_new/testimonial_6.xml',
        'views/snippets/testimonials_new/testimonial_7.xml',
        'views/snippets/testimonials_new/testimonial_8.xml',
        'views/snippets/testimonials_new/testimonial_9.xml',
        'views/snippets/testimonials_new/testimonial_10.xml',
        'views/snippets/testimonials_new/testimonial_11.xml',
        'views/snippets/testimonials_new/testimonial_12.xml',
        'views/snippets/testimonials_new/testimonial_13.xml',
        'views/snippets/testimonials_new/testimonial_14.xml',
        'views/snippets/testimonials_new/testimonial_15.xml',
        'views/snippets/testimonials_new/testimonial_16.xml',
        'views/snippets/testimonials_new/testimonial_17.xml',
        'views/snippets/testimonials_new/testimonial_18.xml',
        'views/snippets/testimonials_new/testimonial_19.xml',
        'views/snippets/testimonials_new/testimonial_20.xml',

        # Progress Bar
        'views/snippets/progress_bar/progress_bar_1.xml',
        'views/snippets/progress_bar/progress_bar_2.xml',
        'views/snippets/progress_bar/progress_bar_3.xml',
        'views/snippets/progress_bar/progress_bar_4.xml',
        'views/snippets/progress_bar/progress_bar_5.xml',
        'views/snippets/progress_bar/progress_bar_6.xml',
        'views/snippets/progress_bar/progress_bar_7.xml',
        'views/snippets/progress_bar/progress_bar_8.xml',
        'views/snippets/progress_bar/progress_bar_9.xml',
        'views/snippets/progress_bar/progress_bar_10.xml',


        # Price Menu List
        'views/snippets/price_menu/price_menu_1.xml',
        'views/snippets/price_menu/price_menu_2.xml',
        'views/snippets/price_menu/price_menu_3.xml',
        'views/snippets/price_menu/price_menu_4.xml',
        'views/snippets/price_menu/price_menu_5.xml',
        'views/snippets/price_menu/price_menu_6.xml',
        'views/snippets/price_menu/price_menu_7.xml',
        'views/snippets/price_menu/price_menu_8.xml',
        'views/snippets/price_menu/price_menu_9.xml',
        'views/snippets/price_menu/price_menu_10.xml',
        'views/snippets/price_menu/price_menu_11.xml',
        'views/snippets/price_menu/price_menu_12.xml',
        'views/snippets/price_menu/price_menu_13.xml',
        'views/snippets/price_menu/price_menu_14.xml',
        'views/snippets/price_menu/price_menu_15.xml',

        # Pricing Tables New
        'views/snippets/pricing_table_new/pricing_1.xml',
        'views/snippets/pricing_table_new/pricing_2.xml',
        'views/snippets/pricing_table_new/pricing_3.xml',
        'views/snippets/pricing_table_new/pricing_4.xml',
        'views/snippets/pricing_table_new/pricing_5.xml',
        'views/snippets/pricing_table_new/pricing_6.xml',
        'views/snippets/pricing_table_new/pricing_7.xml',
        'views/snippets/pricing_table_new/pricing_8.xml',
        'views/snippets/pricing_table_new/pricing_9.xml',
        'views/snippets/pricing_table_new/pricing_10.xml',
        'views/snippets/pricing_table_new/pricing_11.xml',
        'views/snippets/pricing_table_new/pricing_12.xml',
        'views/snippets/pricing_table_new/pricing_13.xml',
        'views/snippets/pricing_table_new/pricing_14.xml',
        'views/snippets/pricing_table_new/pricing_15.xml',
        'views/snippets/pricing_table_new/pricing_16.xml',
        'views/snippets/pricing_table_new/pricing_17.xml',
        'views/snippets/pricing_table_new/pricing_18.xml',
        'views/snippets/pricing_table_new/pricing_19.xml',
        'views/snippets/pricing_table_new/pricing_20.xml',
        'views/snippets/pricing_table_new/pricing_21.xml',
        'views/snippets/pricing_table_new/pricing_22.xml',
        'views/snippets/pricing_table_new/pricing_23.xml',

        #News
        'views/snippets/news/news_1.xml',
        'views/snippets/news/news_2.xml',
        'views/snippets/news/news_3.xml',
        'views/snippets/news/news_4.xml',
        'views/snippets/news/news_5.xml',

        # CTA New
        'views/snippets/cta_new/cta_1.xml',
        'views/snippets/cta_new/cta_2.xml',
        'views/snippets/cta_new/cta_3.xml',
        'views/snippets/cta_new/cta_4.xml',
        'views/snippets/cta_new/cta_5.xml',
        'views/snippets/cta_new/cta_6.xml',
        'views/snippets/cta_new/cta_7.xml',
        'views/snippets/cta_new/cta_8.xml',
        'views/snippets/cta_new/cta_9.xml',
        'views/snippets/cta_new/cta_10.xml',
        'views/snippets/cta_new/cta_11.xml',
        'views/snippets/cta_new/cta_12.xml',
        'views/snippets/cta_new/cta_13.xml',
        'views/snippets/cta_new/cta_14.xml',
        'views/snippets/cta_new/cta_15.xml',
        'views/snippets/cta_new/cta_16.xml',
        'views/snippets/cta_new/cta_17.xml',

        #Timer Snippets
        'views/snippets/timer/timer.xml',
        'views/snippets/timer/timer_1.xml',
        'views/snippets/timer/timer_2.xml',
        'views/snippets/timer/timer_3.xml',
        'views/snippets/timer/timer_4.xml',
        'views/snippets/timer/timer_5.xml',
        'views/snippets/timer/timer_6.xml',
        'views/snippets/timer/timer_7.xml',
        'views/snippets/timer/timer_8.xml',
        'views/snippets/timer/timer_9.xml',
        'views/snippets/timer/timer_10.xml',

        #Blockquotes Snippets
        'views/snippets/blockquotes/blockquote_1.xml',
        'views/snippets/blockquotes/blockquote_2.xml',
        'views/snippets/blockquotes/blockquote_3.xml',
        'views/snippets/blockquotes/blockquote_4.xml',
        'views/snippets/blockquotes/blockquote_5.xml',
        'views/snippets/blockquotes/blockquote_6.xml',
        'views/snippets/blockquotes/blockquote_7.xml',
        'views/snippets/blockquotes/blockquote_8.xml',
        'views/snippets/blockquotes/blockquote_9.xml',
        'views/snippets/blockquotes/blockquote_10.xml',

        # Flip Box
        'views/snippets/flip_box/flip_box_1.xml',
        'views/snippets/flip_box/flip_box_2.xml',
        'views/snippets/flip_box/flip_box_3.xml',
        'views/snippets/flip_box/flip_box_4.xml',
        'views/snippets/flip_box/flip_box_5.xml',
        'views/snippets/flip_box/flip_box_6.xml',
        'views/snippets/flip_box/flip_box_7.xml',
        'views/snippets/flip_box/flip_box_8.xml',
        'views/snippets/flip_box/flip_box_9.xml',
        'views/snippets/flip_box/flip_box_10.xml',

        # Newsletter
        'views/snippets/newsletter/newsletter_1.xml',
        'views/snippets/newsletter/newsletter_2.xml',
        'views/snippets/newsletter/newsletter_3.xml',
        'views/snippets/newsletter/newsletter_4.xml',
        'views/snippets/newsletter/newsletter_5.xml',
        'views/snippets/newsletter/newsletter_6.xml',
        'views/snippets/newsletter/newsletter_7.xml',
        'views/snippets/newsletter/newsletter_8.xml',

         # Thumbnail Gallery Slider
        'views/snippets/thumbnail_gallery/thumbnail_gallery_1.xml',
        'views/snippets/thumbnail_gallery/thumbnail_gallery_2.xml',
        'views/snippets/thumbnail_gallery/thumbnail_gallery_3.xml',
        'views/snippets/thumbnail_gallery/thumbnail_gallery_4.xml',
        'views/snippets/thumbnail_gallery/thumbnail_gallery_5.xml',
        'views/snippets/thumbnail_gallery/thumbnail_gallery_6.xml',
        'views/snippets/thumbnail_gallery/thumbnail_gallery_7.xml',

        #Image Slider
        'views/snippets/image_slider/image_slider_1.xml',
        'views/snippets/image_slider/image_slider_2.xml',
        'views/snippets/image_slider/image_slider_3.xml',
        'views/snippets/image_slider/image_slider_4.xml',
        'views/snippets/image_slider/image_slider_5.xml',
        'views/snippets/image_slider/image_slider_6.xml',
        'views/snippets/image_slider/image_slider_7.xml',
        'views/snippets/image_slider/image_slider_8.xml',
        'views/snippets/image_slider/image_slider_9.xml',
        'views/snippets/image_slider/image_slider_10.xml',

         # Social Share Icons
        'views/snippets/social_share_icons/social_share_icon_1.xml',
        'views/snippets/social_share_icons/social_share_icon_2.xml',
        'views/snippets/social_share_icons/social_share_icon_3.xml',
        'views/snippets/social_share_icons/social_share_icon_4.xml',
        'views/snippets/social_share_icons/social_share_icon_5.xml',
        'views/snippets/social_share_icons/social_share_icon_6.xml',
        'views/snippets/social_share_icons/social_share_icon_7.xml',
        'views/snippets/social_share_icons/social_share_icon_8.xml',
        'views/snippets/social_share_icons/social_share_icon_9.xml',
        'views/snippets/social_share_icons/social_share_icon_10.xml',

        # #Footers Snippets
        'views/snippets/footers/footer_1.xml',
        'views/snippets/footers/footer_2.xml',
        'views/snippets/footers/footer_3.xml',
        'views/snippets/footers/footer_4.xml',
        'views/snippets/footers/footer_5.xml',
        'views/snippets/footers/footer_6.xml',
        'views/snippets/footers/footer_7.xml',
        'views/snippets/footers/footer_8.xml',
        'views/snippets/footers/footer_9.xml',
        'views/snippets/footers/footer_10.xml',
        'views/snippets/footers/footer_11.xml',
        'views/snippets/footers/footer_12.xml',
        'views/snippets/footers/footer_13.xml',
        'views/snippets/footers/footer_14.xml',
        'views/snippets/footers/footer_15.xml',
        'views/snippets/footers/footer_16.xml',
        'views/snippets/footers/footer_17.xml',
        'views/snippets/footers/footer_18.xml',
        'views/snippets/footers/footer_19.xml',
        'views/snippets/footers/footer_20.xml',

    ],
    'demo': [
    ],
    'images': [
    ],
    'depends': [
        'website',
        'website_mass_mailing',
        'website_theme_install',
        # 'website_animate',
        'icon_fonts_73lines',
        'carousel_slider_73lines',
        # 'website_mega_menu_73lines',
        'snippet_boxed_73lines',
        'snippet_client_carousel_73lines',
        
    ],
     'xml':[
		'static/src/xml/snippet_timmer.xml',
	],
    'price': 150,
    'license': 'OPL-1',
    'currency': 'EUR',
    'live_test_url': 'https://www.73lines.com/r/vfd',
    'application': True,
}
